apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: retro-store
  name: retro-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retro-store
  template:
    metadata:
      labels:
        app: retro-store
      name: retro-store
    spec:
      tolerations:
      - key: "os"
        value: "Windows"
        Effect: "NoSchedule"    
      containers:
        - name: web
          image: docker.io/garycncf/retro-store:v1
      nodeSelector:
        beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: retro-store
  labels:
    name: retro-store
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: retro-store
